// API ROUTE INVENTORY - updated Phase 6
// [METHOD] /api/path - status - auth - zod - paginated
// GET /api/ably/auth - active - getServerSession - no - no
// GET /api/admin/analytics - active - getServerSession - no - no
// GET /api/admin/dashboard - active - withAdminAuth - no - no
// GET /api/admin/disputes - stub - requireAdmin - no - yes
// GET /api/admin/env-health - active - getServerSession - no - no
// GET,PUT /api/admin/jobs - active - getServerSession - yes - yes
// POST /api/admin/setup - active - none - no - n/a
// GET /api/admin/stats - active - withAdminAuth - no - no
// GET,PUT /api/admin/users - active - getServerSession - yes - yes
// GET,PUT /api/admin/users/[userId]/[action] - active - getServerSession - yes - yes
// PATCH /api/admin/users/[userId]/suspend - stub - requireAdmin - no - n/a
// PATCH /api/admin/users/[userId]/verify - stub - requireAdmin - no - n/a
// GET,PUT /api/admin/verification - active - getServerSession - yes - yes
// POST /api/analytics/batch - active - none - yes - n/a
// GET,POST /api/analytics/track - active - none - no - no
// POST /api/auth/forgot-password - active - none - yes - n/a
// POST /api/auth/get-context - deleted - none - no - n/a
// POST /api/auth/reset-password - active - none - no - n/a
// POST /api/auth/send-otp - active - getServerSession - no - n/a
// POST /api/auth/set-context - active - none - no - n/a
// POST /api/auth/signup - active - getServerSession - no - n/a
// GET /api/auth/status - active - none - no - no
// POST /api/auth/verify-otp - active - getServerSession - no - n/a
// POST /api/auth/verify-phone-firebase - active - getServerSession - yes - n/a
// POST /api/contact - active - none - no - n/a
// GET /api/dashboard/recent-jobs - active - getServerSession - no - no
// GET /api/dashboard/stats - active - getServerSession - no - no
// GET,POST,PUT /api/disputes - active - getServerSession - no - yes
// GET,POST,PUT /api/disputes/[disputeId] - active - getServerSession - no - yes
// GET /api/fixer/applications - active - getServerSession - yes - yes
// GET /api/health - active - none - no - no
// GET,POST /api/help/feedback - active - getServerSession - no - no
// GET,POST,PUT /api/inngest - active - none - no - n/a
// GET /api/jobs/browse - active - getServerSession - no - yes
// GET,POST,DELETE /api/jobs/drafts - active - getServerSession - no - no
// GET,POST,DELETE /api/jobs/drafts/[draftId] - active - getServerSession - no - no
// GET,POST /api/jobs/post - active - getServerSession - no - no
// GET /api/jobs/saved - stub - requireSession - no - yes
// GET,POST /api/jobs/stats - deleted - getServerSession - no - no
// POST,DELETE /api/jobs/upload-media - active - getServerSession - no - no
// POST,DELETE /api/jobs/[jobId] - active - getServerSession - no - no
// POST,DELETE /api/jobs/[jobId]/applications - active - getServerSession - no - no
// POST,DELETE /api/jobs/[jobId]/applications/withdraw - active - getServerSession - no - no
// POST,DELETE /api/jobs/[jobId]/apply - active - getServerSession - no - no
// POST,DELETE /api/jobs/[jobId]/comments - active - getServerSession - no - no
// POST,DELETE /api/jobs/[jobId]/comments/[commentId] - active - getServerSession - no - no
// POST,DELETE /api/jobs/[jobId]/comments/[commentId]/edit - active - getServerSession - no - no
// POST,DELETE /api/jobs/[jobId]/comments/[commentId]/like - active - getServerSession - no - no
// POST,DELETE /api/jobs/[jobId]/comments/[commentId]/react - active - getServerSession - no - no
// POST,DELETE /api/jobs/[jobId]/like - active - getServerSession - no - no
// POST,DELETE /api/jobs/[jobId]/rating - active - getServerSession - no - no
// POST,DELETE /api/jobs/[jobId]/review - active - getServerSession - no - no
// GET,POST /api/jobs/[jobId]/reviews - stub - requireSession - yes - yes
// POST,DELETE /api/jobs/[jobId]/reviews/status - active - getServerSession - no - no
// POST,DELETE /api/jobs/[jobId]/save - stub - requireSession - no - no
// POST,DELETE /api/jobs/[jobId]/status - active - getServerSession - no - no
// POST,DELETE /api/jobs/[jobId]/view - active - getServerSession - no - no
// GET,POST,PUT,DELETE /api/location - active - getServerSession - yes - no
// GET,POST,DELETE /api/location/cache - deleted - getServerSession - no - no
// POST /api/location/reverse-geocode - active - none - yes - n/a
// GET,POST,PUT,PATCH /api/messages - active - getServerSession - no - no
// GET /api/messages/conversations - active - getServerSession - no - yes
// GET /api/messages/conversations/[conversationId] - active - getServerSession - no - yes
// GET /api/messages/job/[jobId] - active - getServerSession - no - yes
// POST /api/messages/reactions - active - getServerSession - yes - n/a
// GET /api/user/notifications - active - getServerSession - no - yes
// PATCH /api/user/notifications/[id] - active - getServerSession - yes - n/a
// PATCH /api/user/notifications/read-all - active - getServerSession - yes - n/a
// GET,POST,PUT /api/reviews - active - getServerSession - no - yes
// POST /api/reviews/submit - active - getServerSession - no - n/a
// POST /api/reviews/[reviewId]/helpful - active - getServerSession - no - n/a
// GET /api/search/suggestions - active - none - no - no
// POST /api/stripe/webhook - active - webhook - no - n/a
// POST /api/subscription/create-order - active - withAuth - no - n/a
// GET /api/subscription/fixer - active - withAuth - no - no
// GET /api/subscription/hirer - active - withAuth - no - no
// GET /api/subscription/verify-payment - active - withAuth - no - no
// POST /api/upload - active - getServerSession - no - n/a
// POST /api/user/change-email - active - getServerSession - no - n/a
// PUT /api/user/change-password - active - getServerSession - no - n/a
// POST /api/user/check-email - active - getServerSession - yes - n/a
// POST /api/user/check-username - active - getServerSession - no - n/a
// GET /api/user/earnings - active - getServerSession - yes - no
// GET,PUT /api/user/fixer-settings - active - getServerSession - no - no
// GET,POST,PUT,DELETE /api/user/location - active - getServerSession - no - no
// GET,POST /api/user/location/history - active - getServerSession - no - yes
// GET,POST /api/user/notification-preferences - active - getServerSession - yes - no
// GET,POST,PUT,DELETE /api/user/notifications - active - getServerSession - no - yes
// POST /api/user/notifications/read - active - getServerSession - no - n/a
// PUT /api/user/preferences - active - getServerSession - no - n/a
// GET,PUT /api/user/profile - active - getServerSession - no - no
// POST /api/user/profile-photo - active - getServerSession - no - n/a
// GET /api/user/profile/search - active - getServerSession - no - yes
// GET /api/user/profile/[username] - active - getServerSession - no - yes
// GET,PUT,DELETE /api/user/privacy - active - getServerSession - no - no
// GET,POST,DELETE /api/user/push-subscription - active - getServerSession - no - no
// PUT /api/user/update-email - active - getServerSession - yes - n/a
// PUT /api/user/update-phone - active - getServerSession - yes - n/a
// PUT /api/user/update-username - active - getServerSession - no - n/a
// POST /api/user/verification/apply - active - getServerSession - no - n/a
// GET /api/users/[userId]/public - stub - requireSession - no - no
// GET /api/users/[userId]/reviews - stub - requireSession - no - yes
// POST /api/validate-content - active - getServerSession - no - n/a

export * from './response';
export * from './parse';
export * from './auth';
