import { Channels as TypedChannels, Events as TypedEvents } from './events';

export const PRIORITY = {
  LOW: 'low',
  MEDIUM: 'medium',
  HIGH: 'high',
  CRITICAL: 'critical',
} as const;

export const CHANNELS = {
  jobActivity: (jobId: string) => TypedChannels.job(jobId),
  jobUpdates: (jobId: string) => TypedChannels.job(jobId),
  jobComments: (jobId: string) => TypedChannels.job(jobId),
  jobApplications: (jobId: string) => TypedChannels.job(jobId),
  jobQuestions: (jobId: string) => TypedChannels.job(jobId),
  userNotifications: (userId: string) => TypedChannels.user(userId),
  userPresence: (userId: string) => TypedChannels.user(userId),
  userTyping: (userId: string) => TypedChannels.user(userId),
  privateMessage: (jobId: string, hirerId: string, fixerId: string) => {
    const sortedIds = [hirerId, fixerId].sort();
    return TypedChannels.conversation(`job:${jobId}:${sortedIds[0]}:${sortedIds[1]}`);
  },
  conversation: (conversationId: string) => TypedChannels.conversation(conversationId),
  conversationPresence: (conversationId: string) =>
    TypedChannels.conversationPresence(conversationId),
  conversationTyping: (conversationId: string) => TypedChannels.conversation(conversationId),
  newJobs: TypedChannels.marketplace,
  jobFeed: () => TypedChannels.marketplace,
  systemAnnouncements: TypedChannels.marketplace,
  searchTrends: TypedChannels.marketplace,
  searchActivity: TypedChannels.marketplace,
  searchFilters: TypedChannels.marketplace,
  jobStats: TypedChannels.marketplace,
  skillJobs: (_skillName: string) => TypedChannels.marketplace,
  locationJobs: (_city: string, _state: string) => TypedChannels.marketplace,
} as const;

export const EVENTS = {
  JOB_POSTED: TypedEvents.marketplace.jobPosted,
  JOB_UPDATED: TypedEvents.marketplace.jobUpdated,
  JOB_STATUS_CHANGED: TypedEvents.job.statusChanged,
  JOB_DELETED: TypedEvents.marketplace.jobClosed,
  APPLICATION_SUBMITTED: TypedEvents.job.applicationSubmitted,
  APPLICATION_ACCEPTED: TypedEvents.job.applicationAccepted,
  APPLICATION_REJECTED: TypedEvents.job.applicationRejected,
  JOB_ASSIGNED: TypedEvents.job.jobAssigned,
  COMMENT_POSTED: TypedEvents.job.commentPosted,
  COMMENT_LIKED: TypedEvents.job.commentLiked,
  COMMENT_REACTED: TypedEvents.job.commentReacted,
  COMMENT_EDITED: TypedEvents.job.commentEdited,
  COMMENT_REPLIED: TypedEvents.job.commentReplied,
  COMMENT_DELETED: TypedEvents.job.commentDeleted,
  MESSAGE_SENT: TypedEvents.conversation.messageSent,
  MESSAGE_UPDATED: TypedEvents.conversation.messageUpdated,
  MESSAGE_REACTED: TypedEvents.conversation.messageReacted,
  MESSAGE_DELIVERED: TypedEvents.conversation.messageRead,
  MESSAGE_READ: TypedEvents.conversation.messageRead,
  MESSAGES_READ: TypedEvents.conversation.messagesRead,
  MESSAGE_NOTIFICATION: TypedEvents.user.messageNotification,
  CONVERSATION_CREATED: TypedEvents.user.conversationCreated,
  CONVERSATION_UPDATED: TypedEvents.conversation.messageUpdated,
  TYPING_STARTED: TypedEvents.conversation.typingStarted,
  TYPING_STOPPED: TypedEvents.conversation.typingStopped,
  USER_ONLINE: TypedEvents.conversation.typingStarted,
  USER_OFFLINE: TypedEvents.conversation.typingStopped,
  USER_TYPING: TypedEvents.conversation.typingStarted,
  USER_STOPPED_TYPING: TypedEvents.conversation.typingStopped,
  NOTIFICATION_SENT: TypedEvents.user.notificationSent,
  NOTIFICATION_READ: TypedEvents.user.notificationRead,
  NOTIFICATION_DELETED: TypedEvents.user.notificationDeleted,
  SEARCH_PERFORMED: TypedEvents.marketplace.jobUpdated,
  FILTER_CHANGED: TypedEvents.marketplace.jobUpdated,
  FILTERS_RESET: TypedEvents.marketplace.jobUpdated,
  TREND_UPDATED: TypedEvents.marketplace.jobUpdated,
  STATS_UPDATED: TypedEvents.marketplace.jobUpdated,
  SYSTEM_ANNOUNCEMENT: TypedEvents.marketplace.jobUpdated,
  MAINTENANCE_MODE: TypedEvents.marketplace.jobClosed,
  LOCATION_UPDATE_REQUESTED: TypedEvents.user.locationUpdateRequested,
  LOCATION_UPDATED: TypedEvents.user.locationUpdated,
  JOB_SUGGESTIONS_UPDATED: TypedEvents.user.jobSuggestionsUpdated,
} as const;
